### ISSUE TITLE
http://anyaudio.in/ not working on my system

### ISSUE THREAD

**Issue by ShalineeSingh** [iiitv/ShareIt#23]
I'm not sure about the members who worked on this, so I'm mentioning it here. Is there any issue with the site or is it not working on my system? The functionalities are not supposed to be OS specific, are they?

**Comment by yashLadha** [comment]
Which operating are you using ? (just asking)

**Comment by aviaryan** [comment]
@ShalineeSingh The site is live. So this is a problem with just you.
You can open an issue for it here. https://github.com/zeseeit/anyaudio/issues

Also, this repo is meant strictly for sharing resources or important news. So please don't post anything  else here. I say this because lots of people are watching this repo, and every activity that happens here is sent to them as mails. So we really don't want to alert them unnecessarily. 
Therefore, I'm closing this issue now. We can continue this discussion at [zeseeit/anyaudio](https://github.com/zeseeit/anyaudio/issues). 

Thank you
